// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Model.avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class User2 : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"User2\",\"namespace\":\"Model.avro\",\"fields\":[{\"name\":\"first" +
				"name\",\"type\":\"string\"},{\"name\":\"lastname\",\"type\":\"string\"}]}");
		private string _firstname;
		private string _lastname;
		public virtual Schema Schema
		{
			get
			{
				return User2._SCHEMA;
			}
		}
		public string firstname
		{
			get
			{
				return this._firstname;
			}
			set
			{
				this._firstname = value;
			}
		}
		public string lastname
		{
			get
			{
				return this._lastname;
			}
			set
			{
				this._lastname = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.firstname;
			case 1: return this.lastname;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.firstname = (System.String)fieldValue; break;
			case 1: this.lastname = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
